### ISSUE TITLE
Removal of Read Replicas in config.php

### ISSUE THREAD

**Issue by mrashed88** [Azure-Samples/moodle-high-scale#1]
Hello, can we please elaborate why did you remove the read replicas of the database in config.php?

**Comment by deividfoggi** [comment]
It was removed because it's not in use. In the case you add a read-only replica on PostgreSQL, you just go ahead and add the read replica reference in the config.php. Keep in mind that if you are going to use features in Moodle that depends on temp tables, such requests will break if pgbouncer is in transaction mode. You can either keep it in session moodle or consider to have two services + pgbouncer deployment, one in session mode for the writable replica and one in transaction mode for the read-only. Configure the config.php to point to the service that serves pgbouncer pods in transaction mode. Load testing will help to evaluate if this effort pays off for a given scenario.
It's in the backlog to update this architecture reference with read replica in the same AZ and HA enabled in another AZ, which is an architecture already tested.
